version: '3.8'
services:
  db:
    container_name: sa_pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sa_db
    ports:
      - "5433:5432"
  pgadmin:
    container_name: sa_pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"